backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: src/assets
public_folder: ../../assets/

collections:
  - name: "component"
    label: "Component"
    folder: "src/markdowns/"
    create: true
    slug: "{{path}}"
    editor:
      preview: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "components",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Path", name: "path", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      
